
name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  upload-metrics:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: codecov/codecov-action@v4
        with:
          files: on_coverage.dat, repo_coverage.dat
          flags: onboard, repo
          name: coverage
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # - uses: codecov/codecov-action@v4
      #   with:
      #     files: repo_coverage.dat
      #     flags: repo
      #     name: repo
      #     verbose: true
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}